name: Build

on:
  push:
    branches:
      - master
      - develop
  pull_request:

jobs:
  testSDK:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build
      working-directory: ./Sources
      run: xcodebuild -target KinescopeSDK -configuration Debug -sdk iphonesimulator
    - name: Run tests
      working-directory: ./Sources
      run: xcodebuild test -scheme KinescopeSDK -configuration "Debug" -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 8' | xcpretty -c
